# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
  configs:
    full_config:
      height: '500'
      uiColor: '#FCCD'
      toolbarCanCollapse: true
      extraAllowedContent: 'div(*){*}[*];h1(*){*}[*];h2(*){*}[*];p(*){*}[*];hr(*){*}[*];'
      filebrowserBrowseRoute: elfinder
      filebrowserBrowseRouteParameters: []
twig:
  form_themes:
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
